---

- hosts: all

  roles:
  - role: .
    pacman_mirrors:
    - http://arch.yourlabs.org/
    pacman_repositories:
    - name: repo-ck
      url: http://repo-ck.com/$arch
    pacman_keys:
    - 5EE46C4C
